
s='''(id INTEGER, instnm TEXT(100), st_fips INT, region INT, ccbasic INT, ccsizset INT, adm_rate FLOAT, pplus_pct_low FLOAT, pplus_pct_high FLOAT, plus_debt_all_md FLOAT, c150_4 FLOAT, c100_4 FLOAT, trans_4 FLOAT, c150_4_black FLOAT, c150_4_hisp FLOAT, c150_4_nhpi FLOAT, c150_4_aian FLOAT, c150_4_pell FLOAT, ugds_black FLOAT, ugds_hisp FLOAT, ugds_aian FLOAT, ugds_nhpi FLOAT, ugds FLOAT, ind_comp_orig_yr4_rt FLOAT, lo_inc_comp_orig_yr4_rt FLOAT, firstgen_comp_orig_yr4_rt FLOAT, comp_orig_yr4_rt FLOAT, wdraw_orig_yr3_rt FLOAT, ind_wdraw_orig_yr3_rt FLOAT, lo_inc_wdraw_orig_yr3_rt FLOAT, firstgen_wdraw_orig_yr3_rt FLOAT, cuml_debt_p10 FLOAT, cuml_debt_p25 FLOAT, cuml_debt_p75 FLOAT, cuml_debt_p90 FLOAT, npt41_pub FLOAT, npt42_pub FLOAT, npt43_pub FLOAT, npt44_pub FLOAT, npt45_pub FLOAT, npt41_priv FLOAT, npt42_priv FLOAT, npt43_priv FLOAT, npt44_priv FLOAT, npt45_priv FLOAT, pct10_earn_wne_p10 FLOAT, pct25_earn_wne_p10 FLOAT, pct75_earn_wne_p10 FLOAT, pct90_earn_wne_p10 FLOAT, cip25cert2 FLOAT, cip23cert4 FLOAT, cip42bachl FLOAT, weighted_debt_absolute FLOAT, satvr25 FLOAT, social_diversity_score FLOAT, actcm75 FLOAT, pcip45 FLOAT, satwr75 FLOAT, cip46cert4 FLOAT, cip38cert1 FLOAT, npt41_pub_absolute FLOAT, cip01assoc FLOAT, ec_parent_ses_college FLOAT, cip50bachl FLOAT, npt42_pub_relative FLOAT, cip38assoc FLOAT, cip52cert4 FLOAT, cip41assoc FLOAT, pell_ever FLOAT, cip46bachl FLOAT, pcip19 FLOAT, cip49assoc FLOAT, numbranch FLOAT, cip49cert1 FLOAT, cip14cert2 FLOAT, cip45bachl FLOAT, satwr25 FLOAT, control FLOAT, insturl FLOAT, cip05assoc FLOAT, cip13cert2 FLOAT, cip22cert2 FLOAT, plus_debt_inst_comp_md FLOAT, ugds_2mor FLOAT, pcip12 FLOAT, cip10cert4 FLOAT, agege24 FLOAT, accredagency FLOAT, npt43_pub_absolute FLOAT, main FLOAT, npt41_priv_absolute FLOAT, cip10bachl FLOAT, city FLOAT, cip45cert2 FLOAT, plus_debt_all_nocomp_md FLOAT, distanceonly FLOAT, pcip22 FLOAT, debt_mdn FLOAT, cip46cert2 FLOAT, npt41_pub_relative FLOAT, womenonly FLOAT, cip44assoc FLOAT, tribal FLOAT, par_q5 FLOAT, cip26cert1 FLOAT, cip24cert4 FLOAT, cip47cert2 FLOAT, pcip03 FLOAT, pcip43 FLOAT, cip31cert2 FLOAT, actcmmid FLOAT, outcomes_absolute FLOAT, economic_inclusion_score FLOAT, cip49cert2 FLOAT, cip13cert4 FLOAT, cip11cert1 FLOAT, mr_ktop1_pq1 FLOAT, cip11assoc FLOAT, cip41cert1 FLOAT, inventor_pq5 FLOAT, acten75 FLOAT, cip26assoc FLOAT, hcm2 FLOAT, cip03cert4 FLOAT, cip41cert2 FLOAT, cip48cert1 FLOAT, cip44cert4 FLOAT, success_relative FLOAT, pcip42 FLOAT, count FLOAT, cip51bachl FLOAT, pcip47 FLOAT, success_absolute FLOAT, cip40bachl FLOAT, cip01bachl FLOAT, pcip41 FLOAT, social_diversity_score_relative FLOAT, cip40assoc FLOAT, ug FLOAT, cip29assoc FLOAT, total_patents FLOAT, total_cites FLOAT, cip01cert4 FLOAT, cip03bachl FLOAT, pcip23 FLOAT, pcip38 FLOAT, npt43_pub_relative FLOAT, cip23cert1 FLOAT, cip40cert4 FLOAT, cip16cert4 FLOAT, cip44cert1 FLOAT, pcip50 FLOAT, pcip14 FLOAT, pcip39 FLOAT, pcip05 FLOAT, cip30bachl FLOAT, cip14assoc FLOAT, cip19cert2 FLOAT, cip52bachl FLOAT, hsi FLOAT, cip23assoc FLOAT, cip09cert1 FLOAT, economic_inclusion_score_absolute FLOAT, cip11cert4 FLOAT, actmt25 FLOAT, cip39cert1 FLOAT, cip09cert2 FLOAT, par_q2 FLOAT, ugds_nra FLOAT, npt42_pub_absolute FLOAT, cip19cert1 FLOAT, cip11cert2 FLOAT, par_q1 FLOAT, ugds_asian FLOAT, cip50cert2 FLOAT, unitid FLOAT, satmt25 FLOAT, npt45_pub_absolute FLOAT, cip13bachl FLOAT, enrl_orig_yr3_rt FLOAT, par_top5pc FLOAT, ec_high_parent_ses_college FLOAT, pcip16 FLOAT, cip12assoc FLOAT, pcip49 FLOAT, cip51cert4 FLOAT, cip26cert4 FLOAT, cip42cert1 FLOAT, cip23cert2 FLOAT, weighted_debt_relative FLOAT, locale FLOAT, nanti FLOAT, satmt75 FLOAT, count_pq5 FLOAT, inventor_pq2 FLOAT, par_q4 FLOAT, cip30cert4 FLOAT, satmtmid FLOAT, cip29cert4 FLOAT, cip29cert1 FLOAT, sat_avg FLOAT, preddeg FLOAT, cip47cert1 FLOAT, school_x FLOAT, cip19assoc FLOAT, pcip27 FLOAT, cip30cert2 FLOAT, cip48bachl FLOAT, cip50cert4 FLOAT, relaffil FLOAT, cip27bachl FLOAT, satwrmid FLOAT, pcip01 FLOAT, cip01cert1 FLOAT, parent_plus_loan_debt_absolute FLOAT, cip16cert2 FLOAT, cip39cert4 FLOAT, cip25cert4 FLOAT, cip48assoc FLOAT, opeid6 FLOAT, cip49bachl FLOAT, parent_plus_loan_debt_relative FLOAT, satvr75 FLOAT, cip10assoc FLOAT, cip41bachl FLOAT, weighted_income_absolute FLOAT, acten25 FLOAT, cip54cert2 FLOAT, npt45_priv_relative FLOAT, cip38bachl FLOAT, cip16assoc FLOAT, cip52assoc FLOAT, cip27cert4 FLOAT, cip54bachl FLOAT, cip39bachl FLOAT, cip25assoc FLOAT, cip19bachl FLOAT, cip10cert1 FLOAT, cip03cert2 FLOAT, cip27cert2 FLOAT, satvrmid FLOAT, cip12cert2 FLOAT, cip31cert4 FLOAT, cip22cert4 FLOAT, pcip31 FLOAT, cip48cert2 FLOAT, support_relative FLOAT, cip12bachl FLOAT, ccugprof FLOAT, dependent FLOAT, cip31cert1 FLOAT, count_pq4 FLOAT, support_absolute FLOAT, npt42_priv_relative FLOAT, cip54cert1 FLOAT, cip29cert2 FLOAT, first_gen FLOAT, ugds_white FLOAT, cip09cert4 FLOAT, npt41_priv_relative FLOAT, cip41cert4 FLOAT, k_married FLOAT, npt45_pub_relative FLOAT, inventor_pq4 FLOAT, pcip10 FLOAT, actmtmid FLOAT, cip46assoc FLOAT, cip14bachl FLOAT, outcomes_relative FLOAT, cip39assoc FLOAT, cip09bachl FLOAT, cip43bachl FLOAT, cip27cert1 FLOAT, cip48cert4 FLOAT, pcip26 FLOAT, cip05cert2 FLOAT, actwrmid FLOAT, cip42cert4 FLOAT, cip12cert4 FLOAT, mr_kq5_pq1 FLOAT, zip FLOAT, cip27assoc FLOAT, cip26cert2 FLOAT, annhi FLOAT, cip30cert1 FLOAT, weighted_income_relative FLOAT, count_pq3 FLOAT, cip38cert2 FLOAT, cip29bachl FLOAT, cip09assoc FLOAT, cip22cert1 FLOAT, cip16bachl FLOAT, cip25cert1 FLOAT, cip45assoc FLOAT, social_diversity_score_absolute FLOAT, stabbr FLOAT, menonly FLOAT, par_q3 FLOAT, economic_inclusion_score_relative FLOAT, npt45_priv_absolute FLOAT, cip14cert1 FLOAT, locale2 FLOAT, cip47assoc FLOAT, npcurl FLOAT, pcip48 FLOAT, cip22assoc FLOAT, cip51assoc FLOAT, cip15assoc FLOAT, pcip09 FLOAT, cip43cert1 FLOAT, cip01cert2 FLOAT, cip45cert4 FLOAT, pcip11 FLOAT, actmt75 FLOAT, cip04assoc FLOAT, npt44_priv_relative FLOAT, cip12cert1 FLOAT, cip24bachl FLOAT, cip54assoc FLOAT, pcip13 FLOAT, cip24assoc FLOAT, cip45cert1 FLOAT, cip42cert2 FLOAT, highdeg FLOAT, cip23bachl FLOAT, cip31bachl FLOAT, cip04cert1 FLOAT, cip47cert4 FLOAT, actcm25 FLOAT, cip46cert1 FLOAT, pcip51 FLOAT, cip47bachl FLOAT, cip44cert2 FLOAT, pcip24 FLOAT, inventor_pq1 FLOAT, par_top10pc FLOAT, pcip44 FLOAT, cip14cert4 FLOAT, actenmid FLOAT, cip38cert4 FLOAT, pcip52 FLOAT, cip26bachl FLOAT, cip54cert4 FLOAT, npt44_priv_absolute FLOAT, cip03assoc FLOAT, npt44_pub_relative FLOAT, pcip54 FLOAT, superopeid FLOAT, cip51cert1 FLOAT, pcip40 FLOAT, pbi FLOAT, cip05bachl FLOAT, cip05cert4 FLOAT, cip15cert1 FLOAT, pcip15 FLOAT, cip24cert1 FLOAT, cip52cert2 FLOAT, cip04cert2 FLOAT, cip11bachl FLOAT, cip16cert1 FLOAT, cip19cert4 FLOAT, cip15cert2 FLOAT, cip25bachl FLOAT, sat_avg_all FLOAT, count_pq2 FLOAT, pcip46 FLOAT, inventor_pq3 FLOAT, pcip25 FLOAT, cip39cert2 FLOAT, inventor FLOAT, cip40cert2 FLOAT, cip50assoc FLOAT, npt43_priv_relative FLOAT, sch_deg FLOAT, cip31assoc FLOAT, npt44_pub_absolute FLOAT, hbcu FLOAT, cip40cert1 FLOAT, cip44bachl FLOAT, cip13assoc FLOAT, cip05cert1 FLOAT, actwr25 FLOAT, npt43_priv_absolute FLOAT, cip51cert2 FLOAT, cip10cert2 FLOAT, cip13cert1 FLOAT, pcip04 FLOAT, aanapii FLOAT, cip30assoc FLOAT, cip04cert4 FLOAT, cip49cert4 FLOAT, par_top1pc FLOAT, top5cit FLOAT, cip15bachl FLOAT, cip04bachl FLOAT, cip50cert1 FLOAT, par_toppt1pc FLOAT, opeid FLOAT, npt42_priv_absolute FLOAT, cip43cert4 FLOAT, adm_rate_all FLOAT, actwr75 FLOAT, cip42assoc FLOAT, cip43assoc FLOAT, pcip30 FLOAT, cip03cert1 FLOAT, cip15cert4 FLOAT, enrl_orig_yr2_rt FLOAT, count_pq1 FLOAT, pcip29 FLOAT, longitude FLOAT, latitude FLOAT, comp_orig_yr3_rt FLOAT, cip43cert2 FLOAT, cip24cert2 FLOAT, cip52cert1 FLOAT, cip22bachl FLOAT, )
'''

s2 = '''| id                                | int   | YES  |     | NULL    |       |
| instnm                            | text  | YES  |     | NULL    |       |
| st_fips                           | int   | YES  |     | NULL    |       |
| region                            | int   | YES  |     | NULL    |       |
| ccbasic                           | int   | YES  |     | NULL    |       |
| ccsizset                          | int   | YES  |     | NULL    |       |
| adm_rate                          | float | YES  |     | NULL    |       |
| pplus_pct_low                     | float | YES  |     | NULL    |       |
| pplus_pct_high                    | float | YES  |     | NULL    |       |
| plus_debt_all_md                  | float | YES  |     | NULL    |       |
| c150_4                            | float | YES  |     | NULL    |       |
| c100_4                            | float | YES  |     | NULL    |       |
| trans_4                           | float | YES  |     | NULL    |       |
| c150_4_black                      | float | YES  |     | NULL    |       |
| c150_4_hisp                       | float | YES  |     | NULL    |       |
| c150_4_nhpi                       | float | YES  |     | NULL    |       |
| c150_4_aian                       | float | YES  |     | NULL    |       |
| c150_4_pell                       | float | YES  |     | NULL    |       |
| ugds_black                        | float | YES  |     | NULL    |       |
| ugds_hisp                         | float | YES  |     | NULL    |       |
| ugds_aian                         | float | YES  |     | NULL    |       |
| ugds_nhpi                         | float | YES  |     | NULL    |       |
| ugds                              | float | YES  |     | NULL    |       |
| ind_comp_orig_yr4_rt              | float | YES  |     | NULL    |       |
| lo_inc_comp_orig_yr4_rt           | float | YES  |     | NULL    |       |
| firstgen_comp_orig_yr4_rt         | float | YES  |     | NULL    |       |
| comp_orig_yr4_rt                  | float | YES  |     | NULL    |       |
| wdraw_orig_yr3_rt                 | float | YES  |     | NULL    |       |
| ind_wdraw_orig_yr3_rt             | float | YES  |     | NULL    |       |
| lo_inc_wdraw_orig_yr3_rt          | float | YES  |     | NULL    |       |
| firstgen_wdraw_orig_yr3_rt        | float | YES  |     | NULL    |       |
| cuml_debt_p10                     | float | YES  |     | NULL    |       |
| cuml_debt_p25                     | float | YES  |     | NULL    |       |
| cuml_debt_p75                     | float | YES  |     | NULL    |       |
| cuml_debt_p90                     | float | YES  |     | NULL    |       |
| npt41_pub                         | float | YES  |     | NULL    |       |
| npt42_pub                         | float | YES  |     | NULL    |       |
| npt43_pub                         | float | YES  |     | NULL    |       |
| npt44_pub                         | float | YES  |     | NULL    |       |
| npt45_pub                         | float | YES  |     | NULL    |       |
| npt41_priv                        | float | YES  |     | NULL    |       |
| npt42_priv                        | float | YES  |     | NULL    |       |
| npt43_priv                        | float | YES  |     | NULL    |       |
| npt44_priv                        | float | YES  |     | NULL    |       |
| npt45_priv                        | float | YES  |     | NULL    |       |
| pct10_earn_wne_p10                | float | YES  |     | NULL    |       |
| pct25_earn_wne_p10                | float | YES  |     | NULL    |       |
| pct75_earn_wne_p10                | float | YES  |     | NULL    |       |
| pct90_earn_wne_p10                | float | YES  |     | NULL    |       |
| cip25cert2                        | float | YES  |     | NULL    |       |
| cip23cert4                        | float | YES  |     | NULL    |       |
| cip42bachl                        | float | YES  |     | NULL    |       |
| weighted_debt_absolute            | float | YES  |     | NULL    |       |
| satvr25                           | float | YES  |     | NULL    |       |
| social_diversity_score            | float | YES  |     | NULL    |       |
| actcm75                           | float | YES  |     | NULL    |       |
| pcip45                            | float | YES  |     | NULL    |       |
| satwr75                           | float | YES  |     | NULL    |       |
| cip46cert4                        | float | YES  |     | NULL    |       |
| cip38cert1                        | float | YES  |     | NULL    |       |
| npt41_pub_absolute                | float | YES  |     | NULL    |       |
| cip01assoc                        | float | YES  |     | NULL    |       |
| ec_parent_ses_college             | float | YES  |     | NULL    |       |
| cip50bachl                        | float | YES  |     | NULL    |       |
| npt42_pub_relative                | float | YES  |     | NULL    |       |
| cip38assoc                        | float | YES  |     | NULL    |       |
| cip52cert4                        | float | YES  |     | NULL    |       |
| cip41assoc                        | float | YES  |     | NULL    |       |
| pell_ever                         | float | YES  |     | NULL    |       |
| cip46bachl                        | float | YES  |     | NULL    |       |
| pcip19                            | float | YES  |     | NULL    |       |
| cip49assoc                        | float | YES  |     | NULL    |       |
| numbranch                         | float | YES  |     | NULL    |       |
| cip49cert1                        | float | YES  |     | NULL    |       |
| cip14cert2                        | float | YES  |     | NULL    |       |
| cip45bachl                        | float | YES  |     | NULL    |       |
| satwr25                           | float | YES  |     | NULL    |       |
| control                           | float | YES  |     | NULL    |       |
| insturl                           | text  | YES  |     | NULL    |       |
| cip05assoc                        | float | YES  |     | NULL    |       |
| cip13cert2                        | float | YES  |     | NULL    |       |
| cip22cert2                        | float | YES  |     | NULL    |       |
| plus_debt_inst_comp_md            | float | YES  |     | NULL    |       |
| ugds_2mor                         | float | YES  |     | NULL    |       |
| pcip12                            | float | YES  |     | NULL    |       |
| cip10cert4                        | float | YES  |     | NULL    |       |
| agege24                           | float | YES  |     | NULL    |       |
| accredagency                      | text  | YES  |     | NULL    |       |
| npt43_pub_absolute                | float | YES  |     | NULL    |       |
| main                              | float | YES  |     | NULL    |       |
| npt41_priv_absolute               | float | YES  |     | NULL    |       |
| cip10bachl                        | float | YES  |     | NULL    |       |
| city                              | text  | YES  |     | NULL    |       |
| cip45cert2                        | float | YES  |     | NULL    |       |
| plus_debt_all_nocomp_md           | float | YES  |     | NULL    |       |
| distanceonly                      | float | YES  |     | NULL    |       |
| pcip22                            | float | YES  |     | NULL    |       |
| debt_mdn                          | float | YES  |     | NULL    |       |
| cip46cert2                        | float | YES  |     | NULL    |       |
| npt41_pub_relative                | float | YES  |     | NULL    |       |
| womenonly                         | float | YES  |     | NULL    |       |
| cip44assoc                        | float | YES  |     | NULL    |       |
| tribal                            | float | YES  |     | NULL    |       |
| par_q5                            | float | YES  |     | NULL    |       |
| cip26cert1                        | float | YES  |     | NULL    |       |
| cip24cert4                        | float | YES  |     | NULL    |       |
| cip47cert2                        | float | YES  |     | NULL    |       |
| pcip03                            | float | YES  |     | NULL    |       |
| pcip43                            | float | YES  |     | NULL    |       |
| cip31cert2                        | float | YES  |     | NULL    |       |
| actcmmid                          | float | YES  |     | NULL    |       |
| outcomes_absolute                 | float | YES  |     | NULL    |       |
| economic_inclusion_score          | float | YES  |     | NULL    |       |
| cip49cert2                        | float | YES  |     | NULL    |       |
| cip13cert4                        | float | YES  |     | NULL    |       |
| cip11cert1                        | float | YES  |     | NULL    |       |
| mr_ktop1_pq1                      | float | YES  |     | NULL    |       |
| cip11assoc                        | float | YES  |     | NULL    |       |
| cip41cert1                        | float | YES  |     | NULL    |       |
| inventor_pq5                      | float | YES  |     | NULL    |       |
| acten75                           | float | YES  |     | NULL    |       |
| cip26assoc                        | float | YES  |     | NULL    |       |
| hcm2                              | float | YES  |     | NULL    |       |
| cip03cert4                        | float | YES  |     | NULL    |       |
| cip41cert2                        | float | YES  |     | NULL    |       |
| cip48cert1                        | float | YES  |     | NULL    |       |
| cip44cert4                        | float | YES  |     | NULL    |       |
| success_relative                  | float | YES  |     | NULL    |       |
| pcip42                            | float | YES  |     | NULL    |       |
| count                             | float | YES  |     | NULL    |       |
| cip51bachl                        | float | YES  |     | NULL    |       |
| pcip47                            | float | YES  |     | NULL    |       |
| success_absolute                  | float | YES  |     | NULL    |       |
| cip40bachl                        | float | YES  |     | NULL    |       |
| cip01bachl                        | float | YES  |     | NULL    |       |
| pcip41                            | float | YES  |     | NULL    |       |
| social_diversity_score_relative   | float | YES  |     | NULL    |       |
| cip40assoc                        | float | YES  |     | NULL    |       |
| ug                                | float | YES  |     | NULL    |       |
| cip29assoc                        | float | YES  |     | NULL    |       |
| total_patents                     | float | YES  |     | NULL    |       |
| total_cites                       | float | YES  |     | NULL    |       |
| cip01cert4                        | float | YES  |     | NULL    |       |
| cip03bachl                        | float | YES  |     | NULL    |       |
| pcip23                            | float | YES  |     | NULL    |       |
| pcip38                            | float | YES  |     | NULL    |       |
| npt43_pub_relative                | float | YES  |     | NULL    |       |
| cip23cert1                        | float | YES  |     | NULL    |       |
| cip40cert4                        | float | YES  |     | NULL    |       |
| cip16cert4                        | float | YES  |     | NULL    |       |
| cip44cert1                        | float | YES  |     | NULL    |       |
| pcip50                            | float | YES  |     | NULL    |       |
| pcip14                            | float | YES  |     | NULL    |       |
| pcip39                            | float | YES  |     | NULL    |       |
| pcip05                            | float | YES  |     | NULL    |       |
| cip30bachl                        | float | YES  |     | NULL    |       |
| cip14assoc                        | float | YES  |     | NULL    |       |
| cip19cert2                        | float | YES  |     | NULL    |       |
| cip52bachl                        | float | YES  |     | NULL    |       |
| hsi                               | float | YES  |     | NULL    |       |
| cip23assoc                        | float | YES  |     | NULL    |       |
| cip09cert1                        | float | YES  |     | NULL    |       |
| economic_inclusion_score_absolute | float | YES  |     | NULL    |       |
| cip11cert4                        | float | YES  |     | NULL    |       |
| actmt25                           | float | YES  |     | NULL    |       |
| cip39cert1                        | float | YES  |     | NULL    |       |
| cip09cert2                        | float | YES  |     | NULL    |       |
| par_q2                            | float | YES  |     | NULL    |       |
| ugds_nra                          | float | YES  |     | NULL    |       |
| npt42_pub_absolute                | float | YES  |     | NULL    |       |
| cip19cert1                        | float | YES  |     | NULL    |       |
| cip11cert2                        | float | YES  |     | NULL    |       |
| par_q1                            | float | YES  |     | NULL    |       |
| ugds_asian                        | float | YES  |     | NULL    |       |
| cip50cert2                        | float | YES  |     | NULL    |       |
| unitid                            | float | YES  |     | NULL    |       |
| satmt25                           | float | YES  |     | NULL    |       |
| npt45_pub_absolute                | float | YES  |     | NULL    |       |
| cip13bachl                        | float | YES  |     | NULL    |       |
| enrl_orig_yr3_rt                  | float | YES  |     | NULL    |       |
| par_top5pc                        | float | YES  |     | NULL    |       |
| ec_high_parent_ses_college        | float | YES  |     | NULL    |       |
| pcip16                            | float | YES  |     | NULL    |       |
| cip12assoc                        | float | YES  |     | NULL    |       |
| pcip49                            | float | YES  |     | NULL    |       |
| cip51cert4                        | float | YES  |     | NULL    |       |
| cip26cert4                        | float | YES  |     | NULL    |       |
| cip42cert1                        | float | YES  |     | NULL    |       |
| cip23cert2                        | float | YES  |     | NULL    |       |
| weighted_debt_relative            | float | YES  |     | NULL    |       |
| locale                            | float | YES  |     | NULL    |       |
| nanti                             | float | YES  |     | NULL    |       |
| satmt75                           | float | YES  |     | NULL    |       |
| count_pq5                         | float | YES  |     | NULL    |       |
| inventor_pq2                      | float | YES  |     | NULL    |       |
| par_q4                            | float | YES  |     | NULL    |       |
| cip30cert4                        | float | YES  |     | NULL    |       |
| satmtmid                          | float | YES  |     | NULL    |       |
| cip29cert4                        | float | YES  |     | NULL    |       |
| cip29cert1                        | float | YES  |     | NULL    |       |
| sat_avg                           | float | YES  |     | NULL    |       |
| preddeg                           | float | YES  |     | NULL    |       |
| cip47cert1                        | float | YES  |     | NULL    |       |
| school_x                          | float | YES  |     | NULL    |       |
| cip19assoc                        | float | YES  |     | NULL    |       |
| pcip27                            | float | YES  |     | NULL    |       |
| cip30cert2                        | float | YES  |     | NULL    |       |
| cip48bachl                        | float | YES  |     | NULL    |       |
| cip50cert4                        | float | YES  |     | NULL    |       |
| relaffil                          | float | YES  |     | NULL    |       |
| cip27bachl                        | float | YES  |     | NULL    |       |
| satwrmid                          | float | YES  |     | NULL    |       |
| pcip01                            | float | YES  |     | NULL    |       |
| cip01cert1                        | float | YES  |     | NULL    |       |
| parent_plus_loan_debt_absolute    | float | YES  |     | NULL    |       |
| cip16cert2                        | float | YES  |     | NULL    |       |
| cip39cert4                        | float | YES  |     | NULL    |       |
| cip25cert4                        | float | YES  |     | NULL    |       |
| cip48assoc                        | float | YES  |     | NULL    |       |
| opeid6                            | float | YES  |     | NULL    |       |
| cip49bachl                        | float | YES  |     | NULL    |       |
| parent_plus_loan_debt_relative    | float | YES  |     | NULL    |       |
| satvr75                           | float | YES  |     | NULL    |       |
| cip10assoc                        | float | YES  |     | NULL    |       |
| cip41bachl                        | float | YES  |     | NULL    |       |
| weighted_income_absolute          | float | YES  |     | NULL    |       |
| acten25                           | float | YES  |     | NULL    |       |
| cip54cert2                        | float | YES  |     | NULL    |       |
| npt45_priv_relative               | float | YES  |     | NULL    |       |
| cip38bachl                        | float | YES  |     | NULL    |       |
| cip16assoc                        | float | YES  |     | NULL    |       |
| cip52assoc                        | float | YES  |     | NULL    |       |
| cip27cert4                        | float | YES  |     | NULL    |       |
| cip54bachl                        | float | YES  |     | NULL    |       |
| cip39bachl                        | float | YES  |     | NULL    |       |
| cip25assoc                        | float | YES  |     | NULL    |       |
| cip19bachl                        | float | YES  |     | NULL    |       |
| cip10cert1                        | float | YES  |     | NULL    |       |
| cip03cert2                        | float | YES  |     | NULL    |       |
| cip27cert2                        | float | YES  |     | NULL    |       |
| satvrmid                          | float | YES  |     | NULL    |       |
| cip12cert2                        | float | YES  |     | NULL    |       |
| cip31cert4                        | float | YES  |     | NULL    |       |
| cip22cert4                        | float | YES  |     | NULL    |       |
| pcip31                            | float | YES  |     | NULL    |       |
| cip48cert2                        | float | YES  |     | NULL    |       |
| support_relative                  | float | YES  |     | NULL    |       |
| cip12bachl                        | float | YES  |     | NULL    |       |
| ccugprof                          | float | YES  |     | NULL    |       |
| dependent                         | float | YES  |     | NULL    |       |
| cip31cert1                        | float | YES  |     | NULL    |       |
| count_pq4                         | float | YES  |     | NULL    |       |
| support_absolute                  | float | YES  |     | NULL    |       |
| npt42_priv_relative               | float | YES  |     | NULL    |       |
| cip54cert1                        | float | YES  |     | NULL    |       |
| cip29cert2                        | float | YES  |     | NULL    |       |
| first_gen                         | float | YES  |     | NULL    |       |
| ugds_white                        | float | YES  |     | NULL    |       |
| cip09cert4                        | float | YES  |     | NULL    |       |
| npt41_priv_relative               | float | YES  |     | NULL    |       |
| cip41cert4                        | float | YES  |     | NULL    |       |
| k_married                         | float | YES  |     | NULL    |       |
| npt45_pub_relative                | float | YES  |     | NULL    |       |
| inventor_pq4                      | float | YES  |     | NULL    |       |
| pcip10                            | float | YES  |     | NULL    |       |
| actmtmid                          | float | YES  |     | NULL    |       |
| cip46assoc                        | float | YES  |     | NULL    |       |
| cip14bachl                        | float | YES  |     | NULL    |       |
| outcomes_relative                 | float | YES  |     | NULL    |       |
| cip39assoc                        | float | YES  |     | NULL    |       |
| cip09bachl                        | float | YES  |     | NULL    |       |
| cip43bachl                        | float | YES  |     | NULL    |       |
| cip27cert1                        | float | YES  |     | NULL    |       |
| cip48cert4                        | float | YES  |     | NULL    |       |
| pcip26                            | float | YES  |     | NULL    |       |
| cip05cert2                        | float | YES  |     | NULL    |       |
| actwrmid                          | float | YES  |     | NULL    |       |
| cip42cert4                        | float | YES  |     | NULL    |       |
| cip12cert4                        | float | YES  |     | NULL    |       |
| mr_kq5_pq1                        | float | YES  |     | NULL    |       |
| zip                               | text  | YES  |     | NULL    |       |
| cip27assoc                        | float | YES  |     | NULL    |       |
| cip26cert2                        | float | YES  |     | NULL    |       |
| annhi                             | float | YES  |     | NULL    |       |
| cip30cert1                        | float | YES  |     | NULL    |       |
| weighted_income_relative          | float | YES  |     | NULL    |       |
| count_pq3                         | float | YES  |     | NULL    |       |
| cip38cert2                        | float | YES  |     | NULL    |       |
| cip29bachl                        | float | YES  |     | NULL    |       |
| cip09assoc                        | float | YES  |     | NULL    |       |
| cip22cert1                        | float | YES  |     | NULL    |       |
| cip16bachl                        | float | YES  |     | NULL    |       |
| cip25cert1                        | float | YES  |     | NULL    |       |
| cip45assoc                        | float | YES  |     | NULL    |       |
| social_diversity_score_absolute   | float | YES  |     | NULL    |       |
| stabbr                            | text  | YES  |     | NULL    |       |
| menonly                           | float | YES  |     | NULL    |       |
| par_q3                            | float | YES  |     | NULL    |       |
| economic_inclusion_score_relative | float | YES  |     | NULL    |       |
| npt45_priv_absolute               | float | YES  |     | NULL    |       |
| cip14cert1                        | float | YES  |     | NULL    |       |
| locale2                           | float | YES  |     | NULL    |       |
| cip47assoc                        | float | YES  |     | NULL    |       |
| npcurl                            | text  | YES  |     | NULL    |       |
| pcip48                            | float | YES  |     | NULL    |       |
| cip22assoc                        | float | YES  |     | NULL    |       |
| cip51assoc                        | float | YES  |     | NULL    |       |
| cip15assoc                        | float | YES  |     | NULL    |       |
| pcip09                            | float | YES  |     | NULL    |       |
| cip43cert1                        | float | YES  |     | NULL    |       |
| cip01cert2                        | float | YES  |     | NULL    |       |
| cip45cert4                        | float | YES  |     | NULL    |       |
| pcip11                            | float | YES  |     | NULL    |       |
| actmt75                           | float | YES  |     | NULL    |       |
| cip04assoc                        | float | YES  |     | NULL    |       |
| npt44_priv_relative               | float | YES  |     | NULL    |       |
| cip12cert1                        | float | YES  |     | NULL    |       |
| cip24bachl                        | float | YES  |     | NULL    |       |
| cip54assoc                        | float | YES  |     | NULL    |       |
| pcip13                            | float | YES  |     | NULL    |       |
| cip24assoc                        | float | YES  |     | NULL    |       |
| cip45cert1                        | float | YES  |     | NULL    |       |
| cip42cert2                        | float | YES  |     | NULL    |       |
| highdeg                           | float | YES  |     | NULL    |       |
| cip23bachl                        | float | YES  |     | NULL    |       |
| cip31bachl                        | float | YES  |     | NULL    |       |
| cip04cert1                        | float | YES  |     | NULL    |       |
| cip47cert4                        | float | YES  |     | NULL    |       |
| actcm25                           | float | YES  |     | NULL    |       |
| cip46cert1                        | float | YES  |     | NULL    |       |
| pcip51                            | float | YES  |     | NULL    |       |
| cip47bachl                        | float | YES  |     | NULL    |       |
| cip44cert2                        | float | YES  |     | NULL    |       |
| pcip24                            | float | YES  |     | NULL    |       |
| inventor_pq1                      | float | YES  |     | NULL    |       |
| par_top10pc                       | float | YES  |     | NULL    |       |
| pcip44                            | float | YES  |     | NULL    |       |
| cip14cert4                        | float | YES  |     | NULL    |       |
| actenmid                          | float | YES  |     | NULL    |       |
| cip38cert4                        | float | YES  |     | NULL    |       |
| pcip52                            | float | YES  |     | NULL    |       |
| cip26bachl                        | float | YES  |     | NULL    |       |
| cip54cert4                        | float | YES  |     | NULL    |       |
| npt44_priv_absolute               | float | YES  |     | NULL    |       |
| cip03assoc                        | float | YES  |     | NULL    |       |
| npt44_pub_relative                | float | YES  |     | NULL    |       |
| pcip54                            | float | YES  |     | NULL    |       |
| superopeid                        | float | YES  |     | NULL    |       |
| cip51cert1                        | float | YES  |     | NULL    |       |
| pcip40                            | float | YES  |     | NULL    |       |
| pbi                               | float | YES  |     | NULL    |       |
| cip05bachl                        | float | YES  |     | NULL    |       |
| cip05cert4                        | float | YES  |     | NULL    |       |
| cip15cert1                        | float | YES  |     | NULL    |       |
| pcip15                            | float | YES  |     | NULL    |       |
| cip24cert1                        | float | YES  |     | NULL    |       |
| cip52cert2                        | float | YES  |     | NULL    |       |
| cip04cert2                        | float | YES  |     | NULL    |       |
| cip11bachl                        | float | YES  |     | NULL    |       |
| cip16cert1                        | float | YES  |     | NULL    |       |
| cip19cert4                        | float | YES  |     | NULL    |       |
| cip15cert2                        | float | YES  |     | NULL    |       |
| cip25bachl                        | float | YES  |     | NULL    |       |
| sat_avg_all                       | float | YES  |     | NULL    |       |
| count_pq2                         | float | YES  |     | NULL    |       |
| pcip46                            | float | YES  |     | NULL    |       |
| inventor_pq3                      | float | YES  |     | NULL    |       |
| pcip25                            | float | YES  |     | NULL    |       |
| cip39cert2                        | float | YES  |     | NULL    |       |
| inventor                          | float | YES  |     | NULL    |       |
| cip40cert2                        | float | YES  |     | NULL    |       |
| cip50assoc                        | float | YES  |     | NULL    |       |
| npt43_priv_relative               | float | YES  |     | NULL    |       |
| sch_deg                           | float | YES  |     | NULL    |       |
| cip31assoc                        | float | YES  |     | NULL    |       |
| npt44_pub_absolute                | float | YES  |     | NULL    |       |
| hbcu                              | float | YES  |     | NULL    |       |
| cip40cert1                        | float | YES  |     | NULL    |       |
| cip44bachl                        | float | YES  |     | NULL    |       |
| cip13assoc                        | float | YES  |     | NULL    |       |
| cip05cert1                        | float | YES  |     | NULL    |       |
| actwr25                           | float | YES  |     | NULL    |       |
| npt43_priv_absolute               | float | YES  |     | NULL    |       |
| cip51cert2                        | float | YES  |     | NULL    |       |
| cip10cert2                        | float | YES  |     | NULL    |       |
| cip13cert1                        | float | YES  |     | NULL    |       |
| pcip04                            | float | YES  |     | NULL    |       |
| aanapii                           | float | YES  |     | NULL    |       |
| cip30assoc                        | float | YES  |     | NULL    |       |
| cip04cert4                        | float | YES  |     | NULL    |       |
| cip49cert4                        | float | YES  |     | NULL    |       |
| par_top1pc                        | float | YES  |     | NULL    |       |
| top5cit                           | float | YES  |     | NULL    |       |
| cip15bachl                        | float | YES  |     | NULL    |       |
| cip04bachl                        | float | YES  |     | NULL    |       |
| cip50cert1                        | float | YES  |     | NULL    |       |
| par_toppt1pc                      | float | YES  |     | NULL    |       |
| opeid                             | float | YES  |     | NULL    |       |
| npt42_priv_absolute               | float | YES  |     | NULL    |       |
| cip43cert4                        | float | YES  |     | NULL    |       |
| adm_rate_all                      | float | YES  |     | NULL    |       |
| actwr75                           | float | YES  |     | NULL    |       |
| cip42assoc                        | float | YES  |     | NULL    |       |
| cip43assoc                        | float | YES  |     | NULL    |       |
| pcip30                            | float | YES  |     | NULL    |       |
| cip03cert1                        | float | YES  |     | NULL    |       |
| cip15cert4                        | float | YES  |     | NULL    |       |
| enrl_orig_yr2_rt                  | float | YES  |     | NULL    |       |
| count_pq1                         | float | YES  |     | NULL    |       |
| pcip29                            | float | YES  |     | NULL    |       |
| longitude                         | float | YES  |     | NULL    |       |
| latitude                          | float | YES  |     | NULL    |       |
| comp_orig_yr3_rt                  | float | YES  |     | NULL    |       |
| cip43cert2                        | float | YES  |     | NULL    |       |
| cip24cert2                        | float | YES  |     | NULL    |       |
| cip52cert1                        | float | YES  |     | NULL    |       |
| cip22bachl                        | float | YES  |     | NULL    |       |
+-----------------------------------+-------+------+-----+---------+'''

def parseByLine(s: str):
    result = list()
    for line in s.split('\n'):
        if (' ' in line):
            col = line.split()[1]
            result.append(col)
    return result
def collectColumnsByOrder(s: str):
    elems = s.split(',')
    result = list()
    for elem in elems:
        result.append(elem.split()[0])
    result[0] = 'id'
    result = result[:-1]
    return result
# print(collectColumnsByOrder(s))
print(parseByLine(s2))